# ??????
spring.datasource.driver-class-name=org.postgresql.Driver

# ???? Tailscale IP5432
spring.datasource.url=jdbc:postgresql://100.77.203.23:3233/postgres

# ???????
spring.datasource.username=postgres
spring.datasource.password=@1qaz@WSX

# ?????????? update?? Hibernate ???????
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.open-in-view=false

# JWT ??1234567890
# ????????????????? 256 bits (32 bytes)
# ????? UUID ?????????
jwt.secret=MySuperSecretKeyForJwtMustBeVeryLongAndSecure848237213832!@#$%^
jwt.expiration=86400000
# Token ??? (??)????? 1 ? (24 * 60 * 60 * 1000)


# ? GCP ??????
gcp.storage.bucket-name=web_my_images
gcp.storage.project-id=gen-lang-client-0612065299
gcp.storage.credentials-path=classpath:gcp-key.json
